Maximbelyj
Alexander091/Infotech2016 pull request #3
Opened 2016-12-05 12:12 UTC by MaximBelyj

Написал программу про Zoo магазин, как мне передали нужно было реализовать несколько классов животных + сделать метод добавления животных в ArrayList.

2016-12-05 16:14 UTC, Alexander091 requested changes

2016-12-05 16:14 UTC, Alexander091 commented on trainings/Cats.java
> +public class Cats implements Animals {
В Java имена классов указываются в единственном числе. 
Экземпляром является всегда конкретное животное имеющее конкретное состояние.

2016-12-05 16:14 UTC, Alexander091 commented on trainings/Cats.java
> +      Random rnd = new Random(System.currentTimeMillis());
Соответственно когда ты создаёшь конкретный экземпляр объекта, то он имеет состояние.
В твоём случае, животные их не имеют, а каждый раз меняются со временем.

Если в твоём понимании это не единичное животное, а какая-то фабрика по клонированию животных, то она должна называться соответствующе. Иначе не понятно что делает класс

2016-12-05 16:14 UTC, Alexander091 commented on trainings/Cats.java
> +    public void animalName(String s) {
Все методы в java это глаголы, а классы это существительные.
printAnimalName(String S) вот какое подходящие название у этого метода.

А вообще обрати внимание на статью по SOLID, которую я скинул в чат.
И ты сразу поймёшь многие ошибки в классе.

2016-12-05 16:14 UTC, Alexander091 commented on trainings/AnimalShop.java
> +                System.out.println("Please, choose name for cat");
Добавь операции кормёжки, игры с животным. 
Возможность купить животное, посмотреть сколько осталось животных в магазине.

2016-12-07 10:58 UTC, Alexander091 requested changes

2016-12-07 10:58 UTC, Alexander091 commented on trainings/zooshopMax/ShopService.java
> +    static ArrayList<Cat> cats = new ArrayList<>();
поля все должны быть private.
Ты не работаешь с поле в статичном контексте, поэтому убери static.

Если ты создашь общего предка для Cat и Dog и перенесёшь общие свойства туда, то можно создать один общий  список с животными

2016-12-07 10:58 UTC, Alexander091 commented on trainings/zooshopMax/ShopService.java
> +        cats.add(x);
Когда магазин покупает, то животных становится больше
А вот когда продаёт, то меньше

реализуй эти две функции

2016-12-07 10:58 UTC, Alexander091 commented on trainings/zooshopMax/ZooShop.java
> +        Cat cat = new Cat();
Сделай управление через консоль.
Мол чтобы у пользователя была возможность выбрать, что же он будет делать, кормить, покупать или ещё что-то

2016-12-08 08:38 UTC, Alexander091 requested changes

2016-12-08 08:38 UTC, Alexander091 commented on trainings/zooshopMax/ShopService.java
> +            numberOfAnimals--;
зачем эта переменная numberOfAnimal? у тебя же есть pet.size()

2016-12-08 08:38 UTC, Alexander091 commented on trainings/zooshopMax/ShopService.java
> +    ArrayList<Animal> pet = new ArrayList<>();
private List<Animal> pet

2016-12-08 08:38 UTC, Alexander091 commented on trainings/zooshopMax/ZooShop.java
> +        System.out.print("1.Play with cat ");
все функции печати интерфейса вынеси в отдельный класс.
У класса должна быть только одна функция: в данном случае, это покупка/продажа животных. 
Печать это другая функция, которая должна быть в другом классе

2016-12-08 08:38 UTC, Alexander091 commented on trainings/zooshopMax/ZooShop.java
> +                serv.sellAnimal(dog);
Выглядит так будто мы покупаем и продаём одно и тоже животное по несколько раз

2016-12-09 12:04 UTC, MaximBelyj commented on trainings/zooshopMax/ShopService.java
> +            numberOfAnimals--;
Это количество животных в магазине

2016-12-09 19:41 UTC, Alexander091 requested changes

2016-12-09 19:41 UTC, Alexander091 commented on trainings/zooshopMax/Animal.java
> +public class Animal {
Класс должен быть абстрактным, чтобы нельзя было создать экземпляры Animal

2016-12-09 19:41 UTC, Alexander091 commented on trainings/zooshopMax/Hello.java
> +public class Hello {
Плохое название класса. 
Название должно отражать основную функцию класса.

2016-12-16 09:20 UTC, Alexander091 approved these changes

2016-12-16 09:21 UTC, merged